### ISSUE TITLE
Final Congratulations page should look different and/or not have a next button

### ISSUE THREAD

**Issue by brlrb** [OregonGEARUP/iOS#10]

**Comment by splons** [comment]
Definitely could spruce the final screen. I think we will want to make the last checkpoint of the last stage of block 10 be a route type checkpoint with no criteria. Then I will change the code to recognize this is the last block and we can do something special. Make sense?

**Comment by splons** [comment]
![screen shot 2017-08-01 at 5 42 39 pm](https://user-images.githubusercontent.com/8424395/28852876-53460e1c-76e1-11e7-801d-95f6206bcdff.png)

**Comment by splons** [comment]
![screen shot 2017-08-30 at 8 49 21 am](https://user-images.githubusercontent.com/8424395/29881711-35fe6238-8d60-11e7-8adb-bbaaa2b1dad7.png)

**Comment by splons** [comment]
Added new styling and animated fireworks!
