### ISSUE TITLE
Adding colleges to MyPlan before checkpoints

### ISSUE THREAD

**Issue by adrienneenriquez** [OregonGEARUP/iOS#13]
When I add a college to My Plan before going through the checkpoints and THEN add a college when the checkpoint prompts me to, the college added during the checkpoint doesn't get translated into My Plan.

**Comment by splons** [comment]
That is the current implementation. The thinking was to not overwrite existing info. Would you like to have the entry in the checkpoints always override any existing info?

**Comment by adrienneenriquez** [comment]
I think it's a tough call. Because overwriting would remove any data already in My Plan, yes?

**Comment by adrienneenriquez** [comment]
We've got a different solution to this -- we'll add brief instructions to the top of each main page. The My Plan page will include a warning that they should start with the checklists to add info.
