### ISSUE TITLE
Duplicate Stage Screens

### ISSUE THREAD

**Issue by adrienneenriquez** [OregonGEARUP/iOS#14]
When clicking on a stage button from the block screen, the next screen loads twice. So, click the button, see the list of checkpoints on the stage, then the screen swipes (on its own) to the left and opens the same screen, ready to go. This has happened for me on stages 7, 8, and 9. Dana had the same issue on stages 5 and 6.

It doesn't happen every time, and neither of us could cause it to happen on command.

**Comment by splons** [comment]
tap multiple times REALLY fast! 
tap on a block other that the most recently viewed

**Comment by splons** [comment]
fixed in build 34
