### ISSUE TITLE
Extra checkpoints at end of blocks

### ISSUE THREAD

**Issue by danabeck** [OregonGEARUP/iOS#16]
For users that select "undocumented" or "non-immigrant visa holder" in b1_s2_cp4, they see two of the final "Let's keep going" checkpoints in Blocks 2, 4, 6 and 7. These blocks all have several branching routes in the next blocks (blocks 3, 5, 7, 8), so I'm guessing it's related to that. Not sure if it's an issue in the JSON or an issue in the code.

**Comment by splons** [comment]
This was a code issue. Fixed in build 36
