### ISSUE TITLE
Incomplete stage

### ISSUE THREAD

**Issue by adrienneenriquez** [OregonGEARUP/iOS#21]
From Dana ...
Block 2, stage 3: 
Went through all checkpoints but doesn't mark as complete. This may be because the first time going through, did not put in date under checkpoint 2.

Adrienne tried to recreate but was unsuccessful.
Dana then tried to recreate but also unsuccessful. So not sure how the bug arose.

**Comment by danabeck** [comment]
Same issue as #23.
