### ISSUE TITLE
Undocumented student can get to FAFSA screen

### ISSUE THREAD

**Issue by adrienneenriquez** [OregonGEARUP/iOS#22]
b1_s2_cp4 is required to move on to the next checkpoint, but you can bypass it if you skip stage 2 and go directly on to stage 3. 

If you do that, and if you continue on to Block 3, the citizen/permanent resident block is loaded. If you then go back to b1_s2_cp4 and choose undocumented or visa holder as your citizenship status, you still keep the incorrect block 3.

If you then move on to block 5, you get the correct one for the chosen citizenship status.

All of this makes sense - we intentionally set it up so that the citizen/FAFSA info is the default for everyone. And once the blocks are loaded, they're loaded - so we wouldn't expect a change in block 1 to load a new block 3. But this isn't ideal. Is there a workaround anyone can think of? Something that "forces" the user to answer b1_s2_cp4 before block 3 is loaded? 

Would moving that question to the final stage in block 1 do it? Because they won't be able to move on to load block 2 if they can't complete the last stage in block 1?

**Comment by danabeck** [comment]
Swapped Stage 2 and Stage 3.
