### ISSUE TITLE
Undocumented/Visa Final Stages Not Showing as Complete

### ISSUE THREAD

**Issue by danabeck** [OregonGEARUP/iOS#23]
For undocumented and visa students (b1_s3_cp4_i2 and i3):

As you go through the checklist, the last stage that has variable routers at the end (in Blocks 2, 4, 6, 7) are not being checked as complete (turning green).

Perhaps somewhat related, if you go through as a "visa", b8_s2_cp1 doesn't load.

**Comment by splons** [comment]
I have fixed this in 1.0.1 build 2
