### ISSUE TITLE
Arrow keys do not work on the keyboard on Get to Know your Colleges

### ISSUE THREAD

**Issue by brlrb** [OregonGEARUP/iOS#4]
Expected: 
When the user is on the final selectable element for text entry, the arrow should not be present.

Current: 
Tapping a arrow on the keyboard has no effect.

Repro:
1) Open any page with multiple text entry fields On any page with text entry fields
2) navigate to the first or last field
3) the first field should have no "back" arrow, and the last field should have no "next" field

**Comment by splons** [comment]
Low priority

**Comment by splons** [comment]
Fixed for version 2.x release (school year 2018/19)
