### ISSUE TITLE
Locking phone breaks the app UI on cards with multiple fields

### ISSUE THREAD

**Issue by brlrb** [OregonGEARUP/iOS#5]
Expected: 
Backgrounding/locking should behave normally when re-opening the app. 

Actual:
Reopening the app after locking it results in a frozen UI and multiple DONE buttons

Repro:
1) Get to 5. Get Money For College: Get to Know Colleges.
2) Card 2 ""Visit Colleges if possible.""
3) Tap the text field (either one)
4) Lock the phone
5) Reopen the app
6) Observe UI"

**Comment by adrienneenriquez** [comment]
Unable to recreate this issue. Can you elaborate?

**Comment by splons** [comment]
I was not able to recreate this either. Substantial changes have been made to the text field and keyboard handling code since Evan's testing.
