### ISSUE TITLE
Can progress passed  selections without hitting Done

### ISSUE THREAD

**Issue by brlrb** [OregonGEARUP/iOS#6]
Expected: 
When a user reaches the end fo a block, s/he should be required to checkbox the DONE button before progressing. 

Actual: 
When a user reaches the end of a block, s/he can progress the block without selecting Done. Only the FAFSA one requires it. We should require it always. 

Repro:
1) Get to the end of a block requiring ""Done""
2) Don't checkmark ""Done""
3) Hit Next
4) Observe you can continue without selecting Done"

**Comment by adrienneenriquez** [comment]
Yes. We made a decision a couple of months ago to severely limit the number of required checkpoints so that students who download/start the app later in the process can access the stages that make sense for their timing.
