### ISSUE TITLE
The "checkbox" can be "Checked" from the small gap in the right corner.

### ISSUE THREAD

**Issue by brlrb** [OregonGEARUP/iOS#7]
Expected:
The "checkbox" should not accept click/tap event when not active

Repro:
1) Go to "Make a list of colleges", 
2) On the second frame box(next step box/partially visible), we can see "checkbox visible", 
3) Tap on the "checkbox" and it will be checked. It is not supposed to be active.

**Comment by splons** [comment]
I believe this is calling out that you can tap on checkboxes on the next checkpoint that is peeking out on the right. Definitely can. But don't see this as a substantial problem.

**Comment by splons** [comment]
this (actually handling taps in general in the previous/next checkpoints) has been fixed in build 36
