### ISSUE TITLE
You can progress beyond "Apply!" with only two checkboxes ticked off

### ISSUE THREAD

**Issue by brlrb** [OregonGEARUP/iOS#8]
Expected:
User should be required to select all checkboxes on the last page of Apply! Before being allowed to continue

Actual: 
User can select fewer than all checkboxes and be allowed to progress

Repro:
1) Advance to Apply! section
2) Tap fewer than all 5 checkboxes
3) Observe you can progress"

**Comment by adrienneenriquez** [comment]
It looks fine as-is to me. Since different colleges have various requirements for applications, requiring all 5 checkboxes doesn't make sense.

**Comment by splons** [comment]
closing as desired
