### ISSUE TITLE
UI issue with the "Decide!" page

### ISSUE THREAD

**Issue by brlrb** [OregonGEARUP/iOS#9]
Expected:
All UI elements should fit on the card

Actual:
The fourth checkbox falls off the page

Repro:
1) Advance to Decide! section
2) Observe UI 
4) The fourth text-box is not even selectable

**Comment by splons** [comment]
I don't see a screen in Decide! stage that has four checkboxes -- there is one with three.

There is a screen with four text entries, it just fits on the iPhone 5/SE size screen. See attached screen shot.

![screen shot 2017-07-26 at 1 52 56 pm](https://user-images.githubusercontent.com/8424395/28643226-002774b8-720a-11e7-996c-a6548c96651f.png)
